### PR TITLE
Debug py

### PR DESCRIPTION
**Pull request by DaddyWesker**
Tutorial to debug python scripts launched inside metta scripts using Pycharm GUI.

@Necr0x0Der

### CODE REVIEW

**Comment by mvpeterson** [comment]
If you want to use the Pycharm IDE for debugging an imported python script, you can just create a "Run/Debug" configuration for the hyperon-experimental/python/hyperon/metta.py script and add a path to your .metta script file as an input parameter.

**Comment by DaddyWesker** [comment]
> If you want to use the Pycharm IDE for debugging an imported python script, you can just create a "Run/Debug" configuration for the hyperon-experimental/python/hyperon/metta.py script and add a path to your .metta script file as an input parameter.

O'kay, probably i can.

**Comment by DaddyWesker** [comment]
@mvpeterson  I've added your variant of debugging.

**Comment by astroseger** [comment]
By the, example will not work since API for import python files has changed.

**Comment by DaddyWesker** [comment]
> By the way, example will not work with the last version since API for import python files has changed.

Really? You tried already?

**Comment by astroseger** [comment]
> > By the way, example will not work with the last version since API for import python files has changed.
> 
> Really? You tried already?

At least for me it doesn't work. I replaced
```
!(extend-py! additional_funcs.py)
```
with
```
!(import! &self additional_funcs)
```
To make it work.

But maybe there are other ways.

**Comment by DaddyWesker** [comment]
I need to check this. Import of py files already changed once. It was
!(extend-py! additional_funcs)
then
!(extend-py! additional_funcs.py)
Now it is import. Okay, I'll check this one and make fixes to .md file.

**Comment by astroseger** [comment]
> I need to check this. Import of py files already changed once. It was !(extend-py! additional_funcs) then !(extend-py! additional_funcs.py) Now it is import. Okay, I'll check this one and make fixes to .md file. I hope this is the last time import changes =)

The API needs to be changed more often so that developers do not relax.

**Comment by DaddyWesker** [comment]
Okay, I've updated the readme file with new import instead of extend-py.

**Comment by Necr0x0Der** [comment]
@astroseger , please approve this PR if/when you think it is ok

**Comment by astroseger** [comment]
I've tried both ways. I find the "Alternative way" more simple.  But in principle both work.

**Review by Necr0x0Der — APPROVED** [review]

**Pull request merged**
