### PR TITLE
puzzle solving example with port of some common predicates from prolog

### PR DESCRIPTION
**Pull request by noskill**
porting simple prolog programs to metta

### CODE REVIEW

**Review by vsbogd — COMMENTED** [review]
@noskill , do you have a reason to represent this example as a Python program? It could be represented as a `.metta` file as far as I see. I think thus example would be a little bit more clear because it would not include MeTTa API related code.

**Comment by noskill** [comment]
@vsbogd when i run `metta puzzle.metta` it hangs forever

**Comment by vsbogd** [comment]
I tried it locally on a latest `main` and it finishes quickly enough.

**Comment by noskill** [comment]
here is truncated log

[log.txt](https://github.com/trueagi-io/metta-examples/files/13413074/log.txt)

**Comment by patham9** [comment]
This is not logic programming style yet, it can be done with a more direct Prolog translation without any let statement just with **is**. (please see Mattermost)

**Review by vsbogd — APPROVED** [review]

**Pull request merged**
